[server]
port = 8501
enableCORS = true
enableXsrfProtection = false

[theme]
primaryColor = "#0052CC"
backgroundColor = "#F6F6F6"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1A1A1A"
font = "sans serif"

[browser]
gatherUsageStats = false